"""Core star schema: dimensions and operational facts (MEADOWOPS-DATA-001).

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-01
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carrier',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('transit_days_min', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('transit_days_max', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('variability', sa.Enum('low', 'medium', 'high', name='variability', schema='live'), nullable=False),
    sa.Column('reliability_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('reliability_pct >= 0 AND reliability_pct <= 100', name='ck_carrier_reliability_pct_range'),
    sa.CheckConstraint('transit_days_min <= transit_days_max', name='ck_carrier_transit_days_ordered'),
    sa.PrimaryKeyConstraint('id'),
    schema='live'
    )
    op.create_table('date_dim',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('is_month_end', sa.Boolean(), nullable=False),
    sa.Column('is_quarter_end', sa.Boolean(), nullable=False),
    sa.Column('is_year_end', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('date'),
    schema='live'
    )
    op.create_table('product',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('corrugated_packaging', 'protective_packaging', 'shipping_labeling_supplies', name='product_category', schema='live'), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('unit_cost >= 0', name='ck_product_unit_cost_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku'),
    schema='live'
    )
    op.create_table('supplier',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category_focus', sa.String(), nullable=False),
    sa.Column('unit_cost_tier', sa.Enum('low', 'mid', 'high', name='cost_tier', schema='live'), nullable=False),
    sa.Column('base_lead_time_days', sa.Integer(), nullable=False),
    sa.Column('lead_time_variability', sa.Enum('low', 'medium', 'high', name='variability', schema='live'), nullable=False),
    sa.Column('historical_otif_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('historical_otif_pct >= 0 AND historical_otif_pct <= 100', name='ck_supplier_otif_pct_range'),
    sa.PrimaryKeyConstraint('id'),
    schema='live'
    )
    op.create_table('warehouse',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('capacity_pallet_positions', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='live'
    )
    op.create_table('customer',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('service_priority', sa.Enum('standard', 'priority', 'critical', name='service_priority', schema='live'), nullable=False),
    sa.Column('warehouse_id', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['warehouse_id'], ['live.warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='live'
    )
    op.create_table('inventory_snapshot',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('warehouse_id', sa.String(), nullable=False),
    sa.Column('quantity_on_hand', sa.Integer(), nullable=False),
    sa.Column('quantity_allocated', sa.Integer(), nullable=False),
    sa.Column('source_system', sa.Enum('erp', 'wms', 'procurement', name='source_system', schema='live'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity_allocated >= 0', name='ck_inventory_snapshot_qalloc_non_negative'),
    sa.CheckConstraint('quantity_on_hand >= 0', name='ck_inventory_snapshot_qoh_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['live.product.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['live.warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', 'product_id', 'warehouse_id', name='uq_inventory_snapshot_grain'),
    schema='live'
    )
    op.create_table('inventory_transaction',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('transaction_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('warehouse_id', sa.String(), nullable=False),
    sa.Column('transaction_type', sa.Enum('receipt', 'shipment', 'adjustment', 'transfer_in', 'transfer_out', 'cycle_count', name='inventory_transaction_type', schema='live'), nullable=False),
    sa.Column('quantity_delta', sa.Integer(), nullable=False),
    sa.Column('reference_type', sa.String(), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('source_system', sa.Enum('erp', 'wms', 'procurement', name='source_system', schema='live'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['live.product.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['live.warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='live'
    )
    op.create_table('purchase_order',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('po_number', sa.String(), nullable=False),
    sa.Column('supplier_id', sa.String(), nullable=False),
    sa.Column('warehouse_id', sa.String(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('expected_delivery_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'submitted', 'confirmed', 'partially_received', 'received', 'cancelled', name='purchase_order_status', schema='live'), nullable=False),
    sa.Column('source_system', sa.Enum('erp', 'wms', 'procurement', name='source_system', schema='live'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['live.supplier.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['live.warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('po_number'),
    schema='live'
    )
    op.create_table('warehouse_transfer',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('from_warehouse_id', sa.String(), nullable=False),
    sa.Column('to_warehouse_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('transfer_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_transit', 'completed', 'cancelled', name='transfer_status', schema='live'), nullable=False),
    sa.Column('source_system', sa.Enum('erp', 'wms', 'procurement', name='source_system', schema='live'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('from_warehouse_id != to_warehouse_id', name='ck_warehouse_transfer_distinct_warehouses'),
    sa.CheckConstraint('quantity > 0', name='ck_warehouse_transfer_quantity_positive'),
    sa.ForeignKeyConstraint(['from_warehouse_id'], ['live.warehouse.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['live.product.id'], ),
    sa.ForeignKeyConstraint(['to_warehouse_id'], ['live.warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='live'
    )
    op.create_table('purchase_order_line',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('quantity_ordered >= 0', name='ck_po_line_qordered_non_negative'),
    sa.CheckConstraint('quantity_received >= 0', name='ck_po_line_qreceived_non_negative'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_po_line_unit_cost_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['live.product.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['live.purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='live'
    )
    op.create_table('sales_order',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('so_number', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=False),
    sa.Column('warehouse_id', sa.String(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('requested_date', sa.Date(), nullable=False),
    sa.Column('promised_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'submitted', 'allocated', 'partially_shipped', 'shipped', 'cancelled', name='sales_order_status', schema='live'), nullable=False),
    sa.Column('source_system', sa.Enum('erp', 'wms', 'procurement', name='source_system', schema='live'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['live.customer.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['live.warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('so_number'),
    schema='live'
    )
    op.create_table('sales_order_line',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sales_order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('quantity_ordered', sa.Integer(), nullable=False),
    sa.Column('quantity_shipped', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.CheckConstraint('quantity_ordered >= 0', name='ck_so_line_qordered_non_negative'),
    sa.CheckConstraint('quantity_shipped >= 0', name='ck_so_line_qshipped_non_negative'),
    sa.CheckConstraint('unit_price >= 0', name='ck_so_line_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['product_id'], ['live.product.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['live.sales_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='live'
    )
    op.create_table('shipment',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sales_order_id', sa.UUID(), nullable=False),
    sa.Column('carrier_id', sa.String(), nullable=False),
    sa.Column('warehouse_id', sa.String(), nullable=False),
    sa.Column('ship_date', sa.Date(), nullable=False),
    sa.Column('promised_delivery_date', sa.Date(), nullable=False),
    sa.Column('actual_delivery_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'in_transit', 'delivered', 'exception', name='shipment_status', schema='live'), nullable=False),
    sa.Column('source_system', sa.Enum('erp', 'wms', 'procurement', name='source_system', schema='live'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carrier_id'], ['live.carrier.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['live.sales_order.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['live.warehouse.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='live'
    )
    # Code review of Unit 4 (MEADOWOPS-DOM-002): autogenerate picked up
    # future_probe/boundary_probe as "extra tables to drop" because they
    # were ad-hoc scaffolding tables unrelated test runs leaked into the
    # shared dev DB at generation time, not real schema. Dropping/recreating
    # them here (and again in 0003/0004, each redundantly) fails
    # `alembic upgrade head` outright on any fresh database that never had
    # them (no IF EXISTS on op.drop_table) — removed rather than guarded,
    # since these were never part of the real schema in the first place.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipment', schema='live')
    op.drop_table('sales_order_line', schema='live')
    op.drop_table('sales_order', schema='live')
    op.drop_table('purchase_order_line', schema='live')
    op.drop_table('warehouse_transfer', schema='live')
    op.drop_table('purchase_order', schema='live')
    op.drop_table('inventory_transaction', schema='live')
    op.drop_table('inventory_snapshot', schema='live')
    op.drop_table('customer', schema='live')
    op.drop_table('warehouse', schema='live')
    op.drop_table('supplier', schema='live')
    op.drop_table('product', schema='live')
    op.drop_table('date_dim', schema='live')
    op.drop_table('carrier', schema='live')
    # ### end Alembic commands ###

    # autogenerate's drop_table calls don't emit DROP TYPE for the Postgres
    # ENUMs those columns used (a known Alembic/SQLAlchemy limitation) —
    # left alone, a downgrade -> upgrade cycle on the same database fails
    # with "type already exists" (security review, Unit 2). Drop explicitly,
    # after all the table drops above (a type can't be dropped while a
    # table still references it).
    for enum_name in (
        "shipment_status",
        "transfer_status",
        "sales_order_status",
        "purchase_order_status",
        "inventory_transaction_type",
        "source_system",
        "service_priority",
        "variability",
        "cost_tier",
        "product_category",
    ):
        op.execute(f"DROP TYPE IF EXISTS live.{enum_name}")
