"""Decision and Event Ledger (MEADOWOPS-DOM-001, PRD 4.4).

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-01
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0003'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_event',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('record_type', sa.Enum('operational_event', 'decision', name='record_type', schema='live'), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'clarification_requested', 'accepted', 'rejected', 'implemented', 'partially_implemented', 'outcome_observed', 'stale', name='decision_event_status', schema='live'), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('proposed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('approval_authority', sa.Enum('manager', 'procurement_operations', 'informational_only', name='approval_authority', schema='live'), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('implemented_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome', sa.Enum('succeeded', 'partially_succeeded', 'failed', 'unintended_consequence', 'insufficient_evidence', name='decision_outcome', schema='live'), nullable=True),
    sa.Column('outcome_recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('stale_flagged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('supersedes_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['supersedes_id'], ['live.decision_event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='live'
    )
    # See 0002's docstring/comment for why the autogenerated
    # future_probe/boundary_probe drop_table calls (repeated here by
    # autogenerate, same leaked-scaffolding-table cause) were removed
    # rather than kept — code review of Unit 4 caught this repeated across
    # 0002-0004 breaking `alembic upgrade head` from a clean database.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decision_event', schema='live')
    # ### end Alembic commands ###

    # See 0002's downgrade() for why this loop exists: autogenerate's
    # drop_table doesn't emit DROP TYPE for the enums those columns used.
    for enum_name in (
        "decision_outcome",
        "approval_authority",
        "decision_event_status",
        "record_type",
    ):
        op.execute(f"DROP TYPE IF EXISTS live.{enum_name}")
