"""World state and simulation clock (MEADOWOPS-DOM-002, PRD 4.2).

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-01
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('simulation_clock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('simulation_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('running', 'paused', name='clock_status', schema='live'), nullable=False),
    sa.Column('last_advanced_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('id = 1', name='ck_simulation_clock_singleton'),
    sa.PrimaryKeyConstraint('id'),
    schema='live'
    )
    op.create_table('world_state',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.Enum('clean_baseline', 'injected_state', 'snapshot', 'reset', 'controlled_event_injection', name='world_state_kind', schema='live'), nullable=False),
    sa.Column('simulation_date', sa.Date(), nullable=False),
    sa.Column('seed', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['live.world_state.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='live'
    )
    # See 0002's docstring/comment: autogenerated future_probe/boundary_probe
    # drop_table calls (leaked test-scaffolding tables, not real schema)
    # removed — code review of Unit 4 caught these repeated calls across
    # 0002-0004 breaking `alembic upgrade head` from a clean database.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('world_state', schema='live')
    op.drop_table('simulation_clock', schema='live')
    # ### end Alembic commands ###

    # See 0002's downgrade() for why this loop exists.
    for enum_name in ("world_state_kind", "clock_status"):
        op.execute(f"DROP TYPE IF EXISTS live.{enum_name}")
