"""Ledger entity_type enum + no-self-supersede check (security review of
MEADOWOPS-DOM-001).

Hand-written ALTER, not autogenerated: regenerating 0003 from scratch would
have required unwinding 0004 first, which kept colliding with leftover
`boundary_probe`/`future_probe` test-scaffolding tables that unrelated test
runs kept recreating between downgrade steps (accidental autogenerate noise
in 0002-0004's downgrade() functions, not real schema — harmless, but not
worth fighting for what is otherwise a normal incremental change). This is
also more representative of how the project will alter existing tables
going forward once real data exists and a downgrade-to-regenerate workflow
stops being an option at all.

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-01
"""

from typing import Sequence, Union

from alembic import op

revision: str = "0005"
down_revision: Union[str, None] = "0004"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(
        "CREATE TYPE live.ledger_entity_type AS ENUM "
        "('supplier', 'warehouse', 'product', 'customer', 'carrier')"
    )
    op.execute(
        "ALTER TABLE live.decision_event "
        "ALTER COLUMN entity_type TYPE live.ledger_entity_type "
        "USING entity_type::live.ledger_entity_type"
    )
    op.execute(
        "ALTER TABLE live.decision_event "
        "ADD CONSTRAINT ck_decision_event_no_self_supersede CHECK (id != supersedes_id)"
    )


def downgrade() -> None:
    op.execute(
        "ALTER TABLE live.decision_event DROP CONSTRAINT ck_decision_event_no_self_supersede"
    )
    op.execute("ALTER TABLE live.decision_event ALTER COLUMN entity_type TYPE varchar")
    op.execute("DROP TYPE live.ledger_entity_type")
