"""Exception engine flag table (MEADOWOPS-DOM-008, S1-FR-4/S1-FR-5).

One row per detected exception across the three categories Unit 10's
exception_rule_threshold already seeds (low_stock/at_risk_po/late_shipment).
`category` is a plain FK into exception_rule_threshold.id rather than a new
enum, since that table is already the runtime-mutable (S1-FR-10) registry
of rule identities.

Hand-written, not autogenerated (same discipline as 0010's docstring):
this migration adds a functional partial unique index
(ux_exception_flag_open_entity) using COALESCE on the nullable
per-category discriminator columns. Postgres treats NULL as distinct from
NULL in a plain unique index, so a naive
`UNIQUE (category, product_id, warehouse_id, purchase_order_id,
shipment_id) WHERE resolved_at IS NULL` would silently allow duplicate
open low-stock flags for the same product/warehouse (both rows' unused
purchase_order_id/shipment_id are NULL, and NULL != NULL for uniqueness
purposes) — the COALESCE-to-empty-string expression index below is what
actually enforces "at most one open flag per entity per category."
Alembic's autogenerate has no support for expression indexes at all, so
this couldn't have come from a raw diff regardless.

first_detected_simulation_date (security review, MEDIUM) is separate from
simulation_date: the latter is overwritten on every re-sync to track the
most recent evaluation that still found the condition true, while the
former is write-once, set only at INSERT — an Analyst-facing exception
queue needs to answer "how long has this been open?" as well as "what's
its current state?", and one column can't hold both.

Revision ID: 0012
Revises: 0011
Create Date: 2026-09-02
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0012"
down_revision: Union[str, None] = "0011"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "exception_flag",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("product_id", sa.String(), nullable=True),
        sa.Column("warehouse_id", sa.String(), nullable=True),
        sa.Column("purchase_order_id", sa.UUID(), nullable=True),
        sa.Column("shipment_id", sa.UUID(), nullable=True),
        sa.Column("simulation_date", sa.Date(), nullable=False),
        sa.Column("first_detected_simulation_date", sa.Date(), nullable=False),
        sa.Column("measured_value", sa.Numeric(10, 2), nullable=True),
        sa.Column("threshold_value", sa.Numeric(10, 2), nullable=False),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["category"], ["live.exception_rule_threshold.id"]),
        sa.ForeignKeyConstraint(["product_id"], ["live.product.id"]),
        sa.ForeignKeyConstraint(["warehouse_id"], ["live.warehouse.id"]),
        sa.ForeignKeyConstraint(["purchase_order_id"], ["live.purchase_order.id"]),
        sa.ForeignKeyConstraint(["shipment_id"], ["live.shipment.id"]),
        sa.PrimaryKeyConstraint("id"),
        schema="live",
    )
    op.execute(
        """
        CREATE UNIQUE INDEX ux_exception_flag_open_entity
        ON live.exception_flag (
            category,
            COALESCE(product_id, ''),
            COALESCE(warehouse_id, ''),
            COALESCE(purchase_order_id::text, ''),
            COALESCE(shipment_id::text, '')
        )
        WHERE resolved_at IS NULL
        """
    )


def downgrade() -> None:
    op.execute("DROP INDEX IF EXISTS live.ux_exception_flag_open_entity")
    op.drop_table("exception_flag", schema="live")
