"""Unit 30c (MEADOWOPS-UI-005, PRD 380): object storage for chat
attachments - "stored in object storage, never in the operational Postgres
database" (PRD 347/380).

Two implementations of the same narrow `AttachmentStorage` Protocol:
`LocalFilesystemAttachmentStorage` (the original, filesystem-backed) and
`R2AttachmentStorage` (Unit 32, MEADOWOPS-INFRA-005 - a real Cloudflare R2
object store, added once Phase 4 actually owns deployment). The Protocol
existed from the start specifically so this swap could happen without
touching app.services.chat_attachments or any route - this module is the
only place that changed. `Settings.attachment_storage_backend`
(app.core.config) selects which one `get_attachment_storage` constructs.

Keys are opaque tokens generated by the caller (app.services.
chat_attachments, uuid4().hex) - never derived from a filename or any other
user-controlled value, so joining a key directly onto the base directory
(local backend) or passing it as an S3 object key (R2 backend) carries no
path-traversal or injection risk.
"""

from pathlib import Path
from typing import Any, Protocol

from botocore.exceptions import ClientError
from fastapi import Request


class AttachmentNotInStorageError(FileNotFoundError):
    """Raised by load() for a key with no corresponding blob. Under the
    local-filesystem backend this is always a bug (a ChatAttachment row
    whose file is missing) - app.api.chat is expected to treat it as a 500,
    not a 404, since a 404 there would imply the row itself doesn't exist.
    Under the R2 backend (Unit 32) the same `NoSuchKey` condition can also
    mean `Settings.r2_bucket_name` points at the wrong/a since-recreated
    bucket - a config error, not necessarily a data-integrity bug - but
    app.api.chat's 500 treatment is still the right response either way:
    both are server-side problems, never something the client caused."""


class AttachmentStorage(Protocol):
    def save(self, key: str, content: bytes) -> None: ...
    def load(self, key: str) -> bytes: ...
    def delete(self, key: str) -> None: ...


class LocalFilesystemAttachmentStorage:
    def __init__(self, base_dir: Path) -> None:
        self._base_dir = base_dir

    def save(self, key: str, content: bytes) -> None:
        self._base_dir.mkdir(parents=True, exist_ok=True)
        (self._base_dir / key).write_bytes(content)

    def load(self, key: str) -> bytes:
        path = self._base_dir / key
        if not path.is_file():
            raise AttachmentNotInStorageError(key)
        return path.read_bytes()

    def delete(self, key: str) -> None:
        (self._base_dir / key).unlink(missing_ok=True)


class R2AttachmentStorage:
    """Cloudflare R2 (S3-compatible) backend - Unit 32 (MEADOWOPS-INFRA-005),
    chosen over a Railway persistent volume so attachment bytes are decoupled
    from the compute container and survive a redeploy (the local-filesystem
    backend above doesn't - found during B1/B2, Phase 3).

    `client` is a boto3 S3 client constructed once at app startup
    (app.main's lifespan) and passed in here, not built fresh per call like
    LocalFilesystemAttachmentStorage - a boto3 client holds real
    connection-pooling state worth keeping, and is documented safe to share
    across threads (verified at this unit's pre-implementation security
    review, decision 1627). The client is always constructed with an
    explicit bounded `botocore.config.Config` (connect/read timeout +
    retries) so a slow or hanging R2 connection can't indefinitely hold a
    threadpool slot shared with every other sync route in this app - a real
    availability risk a local disk write can't produce, flagged at the same
    review.

    The bucket is never made public and no signed/presigned URL is ever
    generated - every read still goes through app.api.chat's
    get_message_attachment_route exactly as it does for the local-filesystem
    backend, so PRD 380's "never executed/interpreted client-side" posture
    (Content-Disposition + X-Content-Type-Options: nosniff, already shipped)
    is unchanged by this swap."""

    def __init__(self, bucket: str, client: Any) -> None:
        self._bucket = bucket
        self._client = client

    def save(self, key: str, content: bytes) -> None:
        self._client.put_object(Bucket=self._bucket, Key=key, Body=content)

    def load(self, key: str) -> bytes:
        try:
            response = self._client.get_object(Bucket=self._bucket, Key=key)
        except ClientError as exc:
            # Only NoSuchKey is folded into "the blob is missing" (security
            # review, this unit) - every other ClientError code (AccessDenied,
            # NoSuchBucket, throttling, ...) propagates unmapped rather than
            # being misattributed as a data-integrity bug it isn't.
            if exc.response.get("Error", {}).get("Code") == "NoSuchKey":
                raise AttachmentNotInStorageError(key) from exc
            raise
        return response["Body"].read()

    def delete(self, key: str) -> None:
        # delete_object is idempotent under S3 semantics - no error on a
        # missing key, matching LocalFilesystemAttachmentStorage's
        # missing_ok=True above.
        self._client.delete_object(Bucket=self._bucket, Key=key)


def get_attachment_storage(request: Request) -> AttachmentStorage:
    """FastAPI dependency. The local backend is constructed fresh per call
    (it holds no connection or other resource worth pooling, same reasoning
    as get_claude_client's counterpart, app.core.claude); the R2 backend
    wraps the single boto3 client app.main's lifespan already built once at
    startup and cached on app.state - never constructed here."""
    settings = request.app.state.settings
    if settings.attachment_storage_backend == "r2":
        assert settings.r2_bucket_name is not None  # enforced by Settings' own validator
        return R2AttachmentStorage(
            bucket=settings.r2_bucket_name,
            client=request.app.state.r2_client,
        )
    return LocalFilesystemAttachmentStorage(Path(settings.attachment_storage_dir))
