"""Unit 30c (MEADOWOPS-UI-005, PRD 380): object storage for chat
attachments - "stored in object storage, never in the operational Postgres
database" (PRD 347/380).

A filesystem-backed implementation, not a real cloud object store: Phase 4
owns actual deployment (PRD 8.2 lists Railway/Render/Fly as still
undecided), and this project runs "one environment... Docker Compose
locally, matches the deployed environment" (8.2) - committing to a specific
S3-compatible provider now would be scoping into a phase that hasn't
started. `AttachmentStorage` is a narrow Protocol specifically so that swap
can happen later (a real S3/R2 adapter) without touching
app.services.chat_attachments or any route - this module is the only place
that would need to change.

Keys are opaque tokens generated by the caller (app.services.
chat_attachments, uuid4().hex) - never derived from a filename or any other
user-controlled value, so joining a key directly onto the base directory
carries no path-traversal risk.
"""

from pathlib import Path
from typing import Protocol

from fastapi import Request


class AttachmentNotInStorageError(FileNotFoundError):
    """Raised by load() for a key with no corresponding file - always a bug
    (a ChatAttachment row whose blob is missing), never a client-facing
    condition; app.api.chat is expected to treat this as a 500, not a 404,
    since a 404 there would imply the row itself doesn't exist."""


class AttachmentStorage(Protocol):
    def save(self, key: str, content: bytes) -> None: ...
    def load(self, key: str) -> bytes: ...
    def delete(self, key: str) -> None: ...


class LocalFilesystemAttachmentStorage:
    def __init__(self, base_dir: Path) -> None:
        self._base_dir = base_dir

    def save(self, key: str, content: bytes) -> None:
        self._base_dir.mkdir(parents=True, exist_ok=True)
        (self._base_dir / key).write_bytes(content)

    def load(self, key: str) -> bytes:
        path = self._base_dir / key
        if not path.is_file():
            raise AttachmentNotInStorageError(key)
        return path.read_bytes()

    def delete(self, key: str) -> None:
        (self._base_dir / key).unlink(missing_ok=True)


def get_attachment_storage(request: Request) -> AttachmentStorage:
    """FastAPI dependency - constructed fresh per call rather than cached on
    app.state, since LocalFilesystemAttachmentStorage holds no connection or
    other resource worth pooling (same reasoning that keeps
    get_claude_client's counterpart simple, app.core.claude)."""
    settings = request.app.state.settings
    return LocalFilesystemAttachmentStorage(Path(settings.attachment_storage_dir))
